source/accounts/urls.py
from django.urls import path
from accounts.views import LoginView, logout_view

from task_app.views.base import IndexView, DetailView, AddView, TaskUpdateView, DeleteTask
from task_app.views.project import ProjectListView, ProjectDetailView, ProjectCreateView

urlpatterns = [
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", logout_view, name='logout'),
]

source/task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_app.urls')),
    path('auth/', include('accounts.urls'))
]

source/task_app/models/project.py
from django.db import models


class Project(models.Model):
    project = models.CharField(verbose_name='Имя проекта', max_length=100, null=False, blank=False)
    description = models.TextField(verbose_name='Описание', max_length=2000, null=False, blank=False)
    start_date = models.DateField(verbose_name='Дата старта', null=False, blank=False)
    finish_date = models.DateField(verbose_name='Дата завершения', null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    changed_at = models.DateTimeField(verbose_name='Дата изменения', auto_now=True)

    def __str__(self) -> str:
        return f'Project - {self.project}, Description - {self.description}, start_date = {self.start_date}'

    def get_tasks(self):
        if self.tasks:
            return self.tasks.order_by('created_at')

source/task_app/models/task.py
from django.db import models


class Task(models.Model):
    project = models.ForeignKey('task_app.Project', related_name='tasks', on_delete=models.CASCADE,
                                verbose_name='Проект', default=1)
    task = models.CharField(verbose_name='Задача', max_length=200, null=False, blank=False)
    description = models.TextField(verbose_name='Описание', max_length=2000, null=False, blank=False)
    status = models.ForeignKey('task_app.Status', verbose_name='Статус', related_name='task', on_delete=models.RESTRICT)
    type = models.ManyToManyField('task_app.Type', verbose_name='Тип задачи', related_name='task')
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    changed_at = models.DateTimeField(verbose_name='Дата изменения', auto_now=True)

    def __str__(self) -> str:
        return f'Task - {self.task}, Description - {self.description}'

source/task_app/views/base.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, UpdateView, DeleteView, ListView, CreateView
from task_app.forms import SearchForm
from task_app.models.task import Task
from task_app.models.project import Project
from task_app.forms import TaskForm
import datetime
from datetime import timedelta
from django.utils.timezone import utc
from django.utils.http import urlencode
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin





now = datetime.datetime.utcnow().replace(tzinfo=utc)

class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'tasks'
    model = Task
    ordering = ['-created_at']
    paginate_by: int = 3
    paginate_orphans: int = 1


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context
    

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(task__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset
    

    def get_search_form(self):
        return SearchForm(self.request.GET)

    
    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class DetailView(TemplateView):
    template_name: str = 'task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = get_object_or_404(Task, pk=kwargs['pk'])
        return context

class AddView(LoginRequiredMixin, CreateView):
    template_name: str = 'add_task.html'
    model = Task
    form_class = TaskForm
    success_url = '/'


    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.is_authenticated:
    #         return redirect('login')
    #     return super(AddView, self ).dispatch(request, *args, **kwargs)
        


    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        form.instance.project = project
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'update_task.html'
    success_url = '/'


class DeleteTask(LoginRequiredMixin, DeleteView):
    model = Task
    template_name: str = 'confirm_delete.html'
    success_url = '/'

source/templates/add_task.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container mx-5">
    <h5>Добавить новую задачу</h5>
    <hr class="line">
  
    <form action="" method="POST" >
        {% csrf_token %}
        {% include 'partials/task_form.html' with button_text='Добавить' task=task %} 
    </form>
</div>
{% endblock %}

source/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{% block title %}Task Tracker {% endblock %}</title>
</head>

<body>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'index_view' %}">Home</a>
                <a class="nav-link" href="{% url 'project_list' %}">Список проектов</a>

                {% if user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="POST">
                        {% csrf_token %}
                        <input class="nav-link" type="submit" value="Выйти">
                    </form>

                {% else %}
                    <a class="nav-link" href="{% url 'login' %} ">Войти</a>
                {% endif %}
                {% block menu %}{% endblock %}
            </div>
        </div>
    </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>

source/templates/confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="col-8 mx-auto">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Удалить задачу?</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{task.task}}</h6>
          <p class="card-text">{{task.description}}</p>
          <p class="card-text">{{task.status}}</p>
          <p class="card-text">{{task.type}}</p>
          <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Да">
            <a href="/" class="btn btn-secondary">Нет</a>
          </form>

        </div>
      </div>
</div>


  {% endblock %}

source/templates/index.html
{% extends 'base.html' %}

{% block content %}


<div class="row my-3">
  <div class="col-8 mx-auto">
    {% if is_paginated %}
    {% include 'partials/pagination.html' %}
    {% endif %}
    {% include 'partials/search.html' %}
    {% for task in tasks %}
    <div class="card my-3">
      <div class="card-header">
        {{task.task}}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{task.description}}</h5>
        <p class="card-text"> {{task.status}} </p>
        <p class="card-text"> {{task.type}} </p>
        <a href="{% url 'task_view' task.pk %}" class="btn btn-primary">Подробнее</a>
        {% if user.is_authenticated %}
          <a href="{% url 'update_task' task.pk %}" class="btn btn-primary">Редактировать</a>
          <a href="{% url 'delete_task' task.pk %}" class="btn btn-primary">Удалить</a>
        {% endif %}
      </div>
    </div>
    {% empty %}
    <p>По данному запросу ничего не найдено</p>
    {% endfor %}

    {% if is_paginated %}

    {% include 'partials/pagination.html' %}

    {% endif %}
  </div>
</div>


{% endblock %}

source/templates/project_add.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container mx-5">
    <h5>Создать новый проект</h5>
    <hr class="line">
  
    <form action="" method="POST" >
        {% csrf_token %}
        {% include 'partials/task_form.html' with button_text='Добавить' task=task %} 
    </form>
</div>
{% endblock %}

source/templates/project_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row my-3">
  <div class="col-10">
    {% if user.is_authenticated %}
    <a href="{% url 'add_task' project.pk %}" class="btn btn btn-primary">Создать новую задачу</a>
    {% endif %}
  </div>
</div>
<div class="row">
    <div class="col-10">
        <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                  Проект: {{project.project}}
                </button>
              </h2>
              <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">Описание: {{project.description}}</div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                  Дата начала
                </button>
              </h2>
              <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">{{project.start_date}}</div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                  Дата окончания
                </button>
              </h2>
              <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">{{project.finish_date}}</div>
              </div>
            </div>

          </div>
    </div>
</div>
<hr>
<h5>Задачи в проекте:</h5>
<div class="row my-3">
  <div class="col-10">
    {% for task in project.get_tasks %}
    <div class="card my-3">
      <div class="card-header">
        {{task.task}}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{task.description}}</h5>
        <p class="card-text"> {{task.status}} </p>
        {% for item in task.type.all %}
        <p class="card-text"> {{item.type}} {% if not forloop.last %}, {% endif %} </p>
        {% endfor %}
        <a href="{% url 'task_view' task.pk %}" class="btn btn-primary">Подробнее</a>
        {% if user.is_authenticated %}
        <a href="{% url 'update_task' task.pk %}" class="btn btn-primary">Редактировать</a>
        <a href="{% url 'delete_task' task.pk %}" class="btn btn-primary">Удалить</a>
        {% endif %}
      </div>
    </div>
    {% empty %}
    <p>По данному запросу ничего не найдено</p>
    {% endfor %}
  </div>
</div>



{% endblock %}

source/templates/projects_list.html
{% extends 'base.html' %}


{% block content %}

<div class="row my-3">
    <div class="col-10">
      {% if user.is_authenticated %}
        <a href="{% url 'add_project' %}" class="btn btn-primary">Создать новый проект</a>
      {% endif %}
    </div>
</div>
<div class="row my-3">
  <div class="col-8 mx-auto">
    {% if is_paginated %}
    {% include 'partials/pagination.html' %}
    {% endif %}
    <h5>Список проектов</h5>
    {% for project in projects %}
    <div class="card my-3">
      <div class="card-header">
        {{project.project}}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{project.description}}</h5>
        <p class="card-text"> {{project.start_date}} </p>
        <p class="card-text"> {{project.finish_date}} </p>

        <a href="{% url 'project_detail' project.pk %}" class="btn btn-primary">Подробнее</a>


      </div>
    </div>
    {% endfor %}
    {% if is_paginated %}

    {% include 'partials/pagination.html' %}

    {% endif %}
  </div>
</div>

{% endblock %}

source/templates/task_view.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-10">
        <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                  Задача: {{task.task}}
                </button>
              </h2>
              <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">Описание: {{task.description}}</div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                  Статус задачи
                </button>
              </h2>
              <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">{{task.status}}</div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                  Тип Задачи
                </button>
              </h2>
              <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">{% for type in task.type.all %} {{type.type}} {% if not forloop.last %}, {% endif %}{% endfor %}</div>
              </div>
            </div>
          </div>
    </div>
</div>
<!-- {{task.project}} -->
{% endblock %}

source/templates/update_task.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container mx-5">
    <h5>Редактировать задачу</h5>
    <hr class="line">
  
    <form action="" method="POST" >
        {% csrf_token %}
        {% include 'partials/task_form.html' with button_text='Редактировать' task=task %} 
    </form>
</div>
{% endblock %}